apply plugin: 'groovy'
apply plugin: 'maven-publish'

repositories {
  jcenter()
  mavenCentral()
}

publishing {
  publications {
    myLibrary(MavenPublication) {
      groupId = 'org.ros2.tools.gradle'
      version = '0.8.6'
      from components.java
    }
  }
  repositories {
    mavenLocal()  // You can publish locally to your Maven repository if needed, or just use it as-is
  }
}

dependencies {
  implementation gradleApi()
  implementation localGroovy()
  if (project.hasProperty("android")) {
    implementation "com.android.tools.build:gradle:7.4"
  }
}